scania-digital-design-system/tegel-angular-demo

src/app/banner/banner.component.html, src/app/banner/banner.component.spec.ts, src/app/banner/banner.component.ts, src/app/pages/components/components.component.html, src/app/pages/components/components.component.ts, src/styles.css, src/utility-classes.css
Fixes: [DTS-1277](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?assignee=63ff6d6c314f5088138187f0&selectedIssue=DTS-1277)
=> feat(banner): manual testing of banner component

src/app/badge/badge.component.html, src/app/badge/badge.component.spec.ts, src/app/badge/badge.component.ts, src/app/pages/components/components.component.html, src/app/pages/components/components.component.ts
Fixes: [DTS-1276](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?assignee=63ff6d6c314f5088138187f0&selectedIssue=DTS-1276)
=> feat(badge): manual testing of Badge

src/app/app-routing.module.ts, src/app/pages/text-page/text-page.component.html, src/app/pages/text-page/text-page.component.ts, src/app/pages/text-subpage/text-subpage.component.html, src/app/pages/text-subpage/text-subpage.component.spec.ts, src/app/pages/text-subpage/text-subpage.component.ts
* Integrated link component
* Added second level text page
=> feat(link): integrate component

src/app/app-routing.module.ts, src/app/app.component.html, src/app/components/block/block.component.css, src/app/pages/chips-page/chips-page.component.html, src/app/pages/chips-page/chips-page.component.ts, src/styles.css
* Integrated chips components in chip page
* Used chip in form and outside of form
* Refactored styling of <main>
* Added utility class for flex-wrap
* Added reset styling for fieldset
=> feat(chips): integrate component

src/app/components/popover-canvas/popover-canvas.component.html, src/app/components/popover-canvas/popover-canvas.component.spec.ts, src/app/components/popover-canvas/popover-canvas.component.ts, src/app/pages/components/components.component.html, src/app/pages/components/components.component.ts
Integrated and manually tested Popover Canvas.
Fixes: https://tegel.atlassian.net/jira/software/projects/CDEP/boards/1?selectedIssue=CDEP-1294 and https://tegel.atlassian.net/jira/software/projects/CDEP/boards/1?selectedIssue=CDEP-1861
=> feat(popover canvas): integrate component

src/app/app.component.css, src/app/app.component.html, src/app/pages/components/components.component.html, src/app/pages/tabs-buttons-page/tabs-buttons-page.component.html, src/app/pages/tabs-buttons-page/tabs-buttons-page.component.ts, src/app/pages/tabs-links-page/tabs-links-page.component.html, src/app/pages/tabs-links-page/tabs-links-page.component.ts, src/app/pages/tabs-subpage/tabs-subpage.component.html, src/app/pages/tabs-subpage/tabs-subpage.component.spec.ts, src/app/pages/tabs-subpage/tabs-subpage.component.ts, src/app/routes/app-routing.module.ts, src/utils.ts
Also fixed some layout inconsistencies / too large margins
=> feat: integrate tabs test

package-lock.json, src/app/components/badge/badge.component.css, src/app/components/badge/badge.component.html, src/app/components/badge/badge.component.ts
Implemented common use cases of badge for testing.
Found one issue that is likely not angular specific; the label slot doesn't work. Created JIRA issue.
=> feat(badge): test component

src/app/components/datetime/datetime.component.html, src/app/components/datetime/datetime.component.spec.ts, src/app/components/datetime/datetime.component.ts, src/app/pages/components/components.component.html, src/app/pages/components/components.component.ts
* Simple integration of component
* Advanced example and testing is done in the form page.
=> feat(datetime): integrated component

src/app/components/accordion/accordion.component.html, src/app/components/accordion/accordion.component.ts
- Fix spacing
- Fix typography
- Remove primary/secondary version (have only one and rely on parent mode switch)
- correct name of events
If you spot something more for cleanup, please write in the comment
=> fix(accordion): clean up

src/app/components/divider/divider.component.html, src/app/components/divider/divider.component.spec.ts, src/app/components/divider/divider.component.ts, src/app/pages/components/components.component.html, src/app/pages/components/components.component.ts
=> feat(divider): integrate component

src/app/components/tooltip/tooltip.component.css, src/app/components/tooltip/tooltip.component.html, src/app/components/tooltip/tooltip.component.spec.ts, src/app/components/tooltip/tooltip.component.ts, src/app/pages/components/components.component.html, src/app/pages/components/components.component.ts, src/utility-classes.css
=> feat(tooltip) integrate component

src/app/components/popover-menu/popover-menu.component.html, src/app/components/popover-menu/popover-menu.component.spec.ts, src/app/components/popover-menu/popover-menu.component.ts, src/app/pages/components/components.component.html, src/app/pages/components/components.component.ts
Integrate and manually test the Popover Menu component.
**Note:** The referenceEl prop does not work as intended in Angular or React environment. Jira story has been created for this.
Fixes: https://tegel.atlassian.net/jira/software/projects/CDEP/boards/1?selectedIssue=CDEP-1295 and https://tegel.atlassian.net/jira/software/projects/CDEP/boards/1?selectedIssue=CDEP-1862
=> feat(popover menu): integrate component

src/app/components/spinner/spinner.component.html, src/app/components/spinner/spinner.component.spec.ts, src/app/components/spinner/spinner.component.ts, src/app/pages/components/components.component.html, src/app/pages/components/components.component.ts, src/app/pages/form/simple-form/simple-form.component.html, src/app/pages/form/simple-form/simple-form.component.scss, src/app/pages/form/simple-form/simple-form.component.ts
Integrate and manually test Spinner component as isolated component and together with simple form.
Fixes: https://tegel.atlassian.net/jira/software/projects/CDEP/boards/1?selectedIssue=CDEP-1299 and https://tegel.atlassian.net/jira/software/projects/CDEP/boards/1?selectedIssue=CDEP-1866
=> feat(spinner): integrate component

src/app/components/message/message.component.html, src/app/components/message/message.component.spec.ts, src/app/components/message/message.component.ts, src/app/pages/components/components.component.html, src/app/pages/components/components.component.ts
=> feat(message): integrated component

src/app/app.component.html, src/app/app.component.ts
=> feat(banner): integrated above header

src/app/app.component.css, src/app/app.component.html, src/app/app.component.ts, src/app/pages/notifications-page/notifications-page.component.html, src/app/pages/notifications-page/notifications-page.component.spec.ts, src/app/pages/notifications-page/notifications-page.component.ts, src/app/pages/settings-page/settings-page.component.html, src/app/pages/settings-page/settings-page.component.spec.ts, src/app/pages/settings-page/settings-page.component.ts, src/app/pages/text-page/text-page.component.spec.ts, src/app/routes/app-routing.module.ts, src/app/services/user-store.service.ts, src/types.ts
* Introduces simple state management with a UserStoreService
* Implemented state in header/side-menu/settings page
=> feat(header/side-menu): introduce simple state

src/app/components/stepper/stepper.component.css, src/app/components/stepper/stepper.component.html, src/app/components/stepper/stepper.component.spec.ts, src/app/components/stepper/stepper.component.ts, src/app/pages/stepper-page/stepper-page.component.html, src/app/pages/stepper-page/stepper-page.component.spec.ts, src/app/pages/stepper-page/stepper-page.component.ts, src/app/routes/app-routing.module.ts
=> feat(stepper): integrate component

src/app/app.component.html, src/app/components/footer/footer.component.html
Moved footer to correct position (on the side of the side-menu)
=> fix(footer): moved to correct position

src/app/components/toggle/toggle.component.spec.ts, src/app/components/toggle/toggle.component.ts, src/app/pages/components/components.component.html, src/app/pages/components/components.component.ts, src/types.ts
- adding `tds-toggle` component
- adding listener to the custom event tdsToggle
- adding tdsToggle to types as Custom event
- adding app-toggle component to the web-component page
=> feat: toggle component integration

src/app/pages/form/dropdown/dropdown.component.html, src/app/pages/form/simple-form/simple-form.component.html, src/app/pages/form/simple-form/simple-form.component.ts
- Manually tested that the dropdowns in the form works. 
- Also added multiselect to reactive form dropdown and verified that works.
- Reindented code with prettier.
Found minor issue and added to JIRA: CDEP-2327
=> feat(dropdown): test some more, re-indent

src/app/pages/table-page/basic-table.component.ts, src/app/pages/table-page/batch-actions-table.component.ts, src/app/pages/table-page/expandable-table.component.ts, src/app/pages/table-page/filter-table.component.ts, src/app/pages/table-page/pagination-table.component.ts, src/app/pages/table-page/sortable-table.component.ts
Updated prop names in Tables to regain functionality.
=> fix(table): update prop names

src/app/pages/about-page/about-page.component.html
Updated description to describe the demo page is in an Angular (rather than React) environment.
Fixes: [CDEP-2579](https://tegel.atlassian.net/jira/software/projects/CDEP/boards/1?selectedIssue=CDEP-2579)
How to test:
1. Go to the Angular demo page through the link below
2. Go to the About us page
3. Verify that the description says it's an Angular application (not React)
=> fix(about us): update description to describe correct framework

src/app/components/chips/chips.component.html
Aligns with: https://tegel-react-demo.netlify.app/
Fixes: https://tegel.atlassian.net/browse/CDEP-2471
=> fix: chip alignement

src/app/components/banner/banner.component.html, src/app/components/banner/banner.component.ts
Aligns with: https://github.com/scania-digital-design-system/tegel-react-demo/pull/135
Fixes: https://tegel.atlassian.net/browse/CDEP-2469
=> fix: banner alignement

src/app/components/spinner/spinner.component.html
Aligns with: https://tegel-react-demo.netlify.app/
Fixes: https://tegel.atlassian.net/browse/CDEP-2480
=> fix: spinner alignement

src/app/components/badge/badge.component.css, src/app/components/badge/badge.component.html
Aligned with: https://github.com/scania-digital-design-system/tegel-react-demo/pull/134
Fixes: https://tegel.atlassian.net/browse/CDEP-2467 & https://tegel.atlassian.net/browse/CDEP-2468
=> fix: badge alignement

src/app/components/toast/toast.component.html
Aligns with: https://tegel-react-demo.netlify.app/
Fixes: https://tegel.atlassian.net/browse/CDEP-2483
=> fix: align toasts

src/app/components/toggle/toggle.component.ts
Aligns with: https://tegel-react-demo.netlify.app/
Fixes: https://tegel.atlassian.net/browse/CDEP-2571
=> fix: align toggle

src/app/services/user-store.service.ts
Aligns with: https://github.com/scania-digital-design-system/tegel-react-demo/pull/142
Fixes: https://tegel.atlassian.net/browse/CDEP-2697
=> fix: user alignment

src/app/components/footer/footer.component.html
Aligns with: https://tegel-react-demo.netlify.app/form
Fixes: https://tegel.atlassian.net/browse/CDEP-2578
=> fix: footer alignment

src/app/pages/form/form.component.html, src/app/pages/form/simple-form/simple-form.component.html, src/app/pages/form/simple-form/simple-form.component.ts
Aligns with: https://github.com/scania-digital-design-system/tegel-react-demo/pull/141
Fixes: https://tegel.atlassian.net/browse/CDEP-2576
=> fix: form-page alignment

src/app/pages/text-page/text-page.component.css, src/app/pages/text-page/text-page.component.html, src/app/pages/text-page/text-page.component.ts
Aligns with: https://tegel-react-demo.netlify.app/text
Fixes: https://tegel.atlassian.net/browse/CDEP-2583
=> fix: text-page alignement

src/app/app.component.html, src/app/components/tabs/tabs.component.ts, src/app/pages/tabs-buttons-page/tabs-buttons-page.component.html, src/app/pages/tabs-buttons-page/tabs-buttons-page.component.ts, src/app/pages/tabs-links-page/tabs-links-page.component.html, src/app/pages/tabs-links-page/tabs-links-page.component.spec.ts, src/app/pages/tabs-links-page/tabs-links-page.component.ts, src/app/pages/tabs-subpage/tabs-subpage.component.html, src/app/pages/tabs-subpage/tabs-subpage.component.ts, src/app/routes/app-routing.module.ts
Aligns with: https://tegel-react-demo.netlify.app/tabs-links
Fixes:
- https://tegel.atlassian.net/browse/CDEP-2481
- https://tegel.atlassian.net/browse/CDEP-2581
- https://tegel.atlassian.net/browse/CDEP-2582
=> fix: tabs pages alignment

src/app/pages/table-page/basic-table.component.ts, src/app/pages/table-page/batch-actions-table.component.ts, src/app/pages/table-page/exampleData.json, src/app/pages/table-page/expandable-table.component.ts, src/app/pages/table-page/filter-table.component.ts, src/app/pages/table-page/pagination-table.component.ts, src/app/pages/table-page/sortable-table.component.ts, src/app/pages/table-page/table-modal.component.ts, src/app/pages/table-page/table-page.component.ts
Aligns with: https://tegel-react-demo.netlify.app/table
Fixes: https://tegel.atlassian.net/browse/CDEP-2580
=> fix: table alignment

src/app/components/popover-menu/popover-menu.component.html
Aligns with: https://tegel-react-demo.netlify.app/web-components
Fixes: https://tegel.atlassian.net/browse/CDEP-2478
=> fix: popper alignment

src/app/components/stepper/stepper.component.ts
Aligns with: https://github.com/scania-digital-design-system/tegel-react-demo/compare/fix/CDEP-2704-stepper-alignment?expand=1
Fixes: https://tegel.atlassian.net/browse/CDEP-2704
=> fix: stepper alignment

src/app/components/accordion/accordion.component.html, src/app/components/block/block.component.html, src/app/components/message/message.component.html, src/app/components/popover-canvas/popover-canvas.component.html, src/app/pages/components/components.component.css, src/app/pages/components/components.component.html, src/app/pages/components/components.component.spec.ts, src/app/pages/components/components.component.ts, src/styles.css
Fixes: https://tegel.atlassian.net/browse/CDEP-2477
Aligns with: https://github.com/scania-digital-design-system/tegel-react-demo/pull/148
=> fix: spacing alignment

src/app/app.component.html, src/app/pages/about-page/about-page.component.html
Fixes: https://tegel.atlassian.net/browse/CDEP-2836
=> fix: updated banner

src/index.html
Enabling Plausible monitoring for the Angular demo page
=> feat: enabling plausible monitoring

package-lock.json, package.json
=> feat(tegel-angular): using version 1.3.0

README.md
Fixes: https://tegel.atlassian.net/jira/software/projects/CDEP/boards/1?assignee=63ff6d6c314f5088138187f0&selectedIssue=CDEP-2898
=> chore: update readme with correct url

package-lock.json, package.json
Bumping version of tegel to 1.4.0
=> feat: tegel@1.4.0

package-lock.json, package.json, src/app/app.component.html
=> feat: tegel@1.5.0

package-lock.json, package.json
=> feat: tegel@1.6.1

src/app/components/dropdown/dropdown.component.html, src/app/components/dropdown/dropdown.component.ts
This question came in from [support](https://teams.microsoft.com/l/message/19:5e33f67fe502441f914fbcdc6e2548f5@thread.skype/1706714894628?tenantId=3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac&groupId=79f9bfeb-73e2-424d-9477-b236191ece5e&parentMessageId=1706714894628&teamName=Tegel%20Design%20System&channelName=Development%20support%20-%20Tegel&createdTime=1706714894628). The solution was not existing as a example so added one.
=> feat: added reset button example from support

package-lock.json, package.json, src/app/pages/table-page/basic-table.component.ts, src/app/pages/table-page/batch-actions-table.component.ts, src/app/pages/table-page/expandable-table.component.ts, src/app/pages/table-page/filter-table.component.ts, src/app/pages/table-page/pagination-table.component.ts, src/app/pages/table-page/sortable-table.component.ts
- using tegel 1.7.0
- table text-align update
=> feat: tegel 1.7.0

package-lock.json, package.json
Using new version of Tegel code
=> feat: tegel-1.8.1

package-lock.json, package.json
=> feat: tegel@1.8.2

package-lock.json, package.json
Bumping Tegel to new version fo code
=> feat: tegel 1.9.1

package-lock.json, package.json
Bumping Tegel to new version fo code
=> feat: tegel 1.10.0

package-lock.json, package.json
Update @scania/tegel-angular version after release
=> feat: tegel 1.11.0

src/app/app.component.html, src/app/pages/ag-grid/ag-grid-editable-cells.component.html, src/app/pages/ag-grid/ag-grid-editable-cells.component.ts, src/app/pages/ag-grid/ag-grid-page.component.ts, src/app/pages/ag-grid/ag-grid.component.html, src/app/pages/ag-grid/ag-grid.component.ts, src/app/routes/app-routing.module.ts, src/assets/styles/main.css
Adding an implementation example of editable cells with AG-Grid.
=> feat(ag-grid): editable cells

package-lock.json, package.json
Update @scania/tegel-angular version after release
=> feat: @scania/tegel-angular 1.12.0

package-lock.json, package.json, src/app/app.component.html, src/app/pages/table-page/pagination-table.component.ts, src/app/pages/table-page/table-page.component.ts, src/app/pages/table-page/zebra-table.component.ts
Adding examples on Table component:
- zebra rows and columns
- rows per page logic
=> feat(table): pagination rows and zebra feature

package-lock.json, package.json
=> feat: tegel 1.18.0

package-lock.json, package.json
=> feat: tegel 1.20.0

package-lock.json
=> build: node 22 upgrade

package-lock.json, package.json
Updates scania/tegel-angular package to version 1.23.0
=> release: version 1.23.0

package-lock.json, package.json
=> release: bump latest version

package-lock.json, package.json
Bump package to newest version.
=> release: bump wrapper version

package-lock.json, package.json
=> release: bump version

package-lock.json, package.json
Update to new version of Tegel
=> feat: tegel 1.35.0

.github/CODEOWNERS
Removed mistermalm from Codeowners file
=> chore(codeowners): removed mistermalm
